---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.10
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[dotfiles::default]
    attributes:
